import { Metadata } from "next";
import QrGeneratorWidget from "./QrGeneratorWidget";
import { TrustSignals, FAQ, ToolHero, SEOContent } from "@/components/seo";
import { ToolSchema, TOOL_META, BreadcrumbSchema } from "@/lib/seo";
import RelatedGuides from "@/components/seo/RelatedGuides";
import Breadcrumbs from "@/components/layout/Breadcrumbs";

export const metadata: Metadata = {
  title:       TOOL_META["qr-code-generator"].title,
  description: TOOL_META["qr-code-generator"].description,
  keywords:    TOOL_META["qr-code-generator"].keywords,
  openGraph: {
    title:       TOOL_META["qr-code-generator"].title,
    description: TOOL_META["qr-code-generator"].description,
    url:         "https://shrink-box.com/qr-code-generator",
    siteName:    "ShrinkBox",
    type:        "website",
    images: [{ url: "https://shrink-box.com/og-image.png", width: 1200, height: 630 }],
  },
  twitter: {
    card:        "summary_large_image",
    title:       TOOL_META["qr-code-generator"].title,
    description: TOOL_META["qr-code-generator"].description,
  },
  alternates: {
    canonical: "/qr-code-generator",
  },
};

const FAQ_ITEMS = [
  { q: "Are the generated QR codes permanent?", a: "Yes. All QR codes generated by ShrinkBox are static, meaning they encode your data directly into the pattern. They will function forever as long as your destination URL or text remains active, with no expiration dates." },
  { q: "Can I customize the look and feel of my QR code?", a: "Absolutely. Our professional generator allows you to customize foreground and background colors to match your brand identity perfectly. You can also adjust the error correction level for maximum readability." },
  { q: "Do these QR codes have scan limits or watermarks?", a: "No. ShrinkBox provides a completely clean, professional experience. There are zero scan limits, zero watermarks, and no annoying redirect pages—just a direct, high-quality QR code image." },
  { q: "Is the data I encode into the QR code private?", a: "Yes. Your privacy is paramount. The entire encoding process happens **locally in your browser**. We never see, store, or track the URLs or text you encode, ensuring 100% data confidentiality." },
];

export default function QrGeneratorPage() {
  return (
    <>
      <ToolSchema
        name={TOOL_META["qr-code-generator"].title}
        description={TOOL_META["qr-code-generator"].description}
        url={TOOL_META["qr-code-generator"].url}
        category={TOOL_META["qr-code-generator"].category}
      />
      <BreadcrumbSchema
        items={[
          { name: "Home", url: "/" },
          { name: "QR Code Generator", url: "/qr-code-generator" },
        ]}
      />
      <section className="max-w-2xl mx-auto px-4 pt-14 pb-8">
        <Breadcrumbs items={[{ name: "QR Code Generator", url: "/qr-code-generator" }]} />
        <ToolHero 
          icon="🔳" 
          title="Free QR Code Generator Online — Custom & Static Codes" 
          description="Create high-resolution, custom QR codes for websites, WiFi networks, or plain text instantly. No signups, no tracking, and 100% free forever." 
          badge="QR Creator · Free · Private" 
        />
        <QrGeneratorWidget />
        <div className="mt-8"><TrustSignals /></div>
      </section>

      <section className="max-w-4xl mx-auto px-4 pb-16">
        <FAQ items={FAQ_ITEMS} />
      </section>

      <SEOContent
        toolName="QR Code Generator"
        title="Free QR Code Generator Online — The Secure Way to Share Links"
        description="Bridge the gap between physical marketing and digital experiences. ShrinkBox provides a fast, browser-based way to generate professional-grade QR codes with zero redirects."
        howToSteps={[
          "Select the type of content you want to encode (URL, Text, or WiFi).",
          "Enter your data into the secure input field provided in the generator.",
          "Customize your QR code colors and design parameters for your project.",
          "Download your high-resolution PNG or SVG file instantly with one click."
        ]}
      >
        <div className="mt-12 space-y-8 text-muted-foreground leading-relaxed">
          <div>
            <h3 className="text-xl font-bold text-foreground mb-4">Why every brand needs static, redirect-free QR codes</h3>
            <p>
              Many 'free' online generators use dynamic redirects, which they can later disable or charge for. ShrinkBox only generates **static QR codes**. This means the data is embedded directly in the visual pattern. Your codes will never expire and will always point exactly where you intended, making them the perfect choice for printed materials like business cards, menus, and posters.
            </p>
          </div>

          <div>
            <h3 className="text-xl font-bold text-foreground mb-4">Complete Privacy: Local Coding Intelligence</h3>
            <p>
              Your links and private network names should stay between you and your customers. ShrinkBox performs the entire QR encoding process **within your own browser**. Your data is never sent to a server for processing, ensuring that your marketing strategies and private info remain confidential and secure.
            </p>
          </div>

          <div className="bg-brand-light/20 p-6 rounded-2xl border border-brand/10">
            <h3 className="text-lg font-bold text-brand mb-2">Pro Tip: Test Scannability</h3>
            <p className="text-sm">
              If you're using dark background colors, ensure there is high contrast between the pattern and the background. Always perform a test scan with your smartphone's camera before sending your QR code to a professional printer to guarantee a perfect user experience.
            </p>
          </div>
        </div>
      </SEOContent>
      <RelatedGuides tags={["Design", "Tools"]} />
    </>
  );
}
