export const BLOG_POSTS = [
  {
    slug:    "how-to-compress-images-for-web",
    title:   "How to Compress Images for the Web Without Losing Quality",
    excerpt: "Large images slow down websites and hurt SEO. Learn exactly how to compress JPG, PNG, and WebP images for fast-loading pages.",
    date:    "2025-01-15",
    readMin: 6,
    tag:     "Images",
  },
  {
    slug:    "reduce-pdf-file-size",
    title:   "5 Ways to Reduce PDF File Size (Free Methods That Actually Work)",
    excerpt: "Email attachment too large? PDF won't upload? Here are five proven methods to reduce PDF file size for free.",
    date:    "2025-01-20",
    readMin: 5,
    tag:     "PDF",
  },
  {
    slug:    "jpg-vs-png-vs-webp",
    title:   "JPG vs PNG vs WebP: Which Format Should You Use?",
    excerpt: "Choosing the right image format can cut your file sizes by 50% or more. Here's a plain-English breakdown.",
    date:    "2025-01-28",
    readMin: 7,
    tag:     "Formats",
  },
  {
    slug:    "compress-images-for-email",
    title:   "How to Compress Images for Email Attachments",
    excerpt: "Most email providers cap attachments at 10–25 MB. Learn how to compress images so they fit without looking bad.",
    date:    "2025-02-03",
    readMin: 4,
    tag:     "Email",
  },
  {
    slug:    "what-is-webp",
    title:   "What Is WebP? Why Google Created a New Image Format",
    excerpt: "WebP is now the most efficient image format for the web. Here's what it is, why it's better, and how to convert your images.",
    date:    "2025-02-10",
    readMin: 5,
    tag:     "Formats",
  },
  {
    slug:    "merge-pdf-guide",
    title:   "How to Merge PDF Files Online for Free (Step-by-Step)",
    excerpt: "Need to combine multiple PDFs into one? This guide shows you how to merge PDFs for free — no software needed.",
    date:    "2025-02-18",
    readMin: 4,
    tag:     "PDF",
  },
  {
    slug:    "how-to-watermark-pdf",
    title:   "How to Add a Watermark to a PDF Online (Free)",
    excerpt: "Protect your documents by adding a custom text watermark to every page of your PDF. Here's how to do it for free in seconds.",
    date:    "2025-03-01",
    readMin: 4,
    tag:     "PDF",
  },
  {
    slug:    "resize-image-online",
    title:   "How to Resize an Image Online Without Losing Quality",
    excerpt: "Need to resize an image for a website, email, or social media? Learn the right way to resize without making it look blurry.",
    date:    "2025-03-08",
    readMin: 5,
    tag:     "Images",
  },
  {
    slug:    "convert-png-to-jpg",
    title:   "How to Convert PNG to JPG Online (and Why You Should)",
    excerpt: "PNG files are great for quality but huge in size. Converting to JPG can reduce size by 5x. Here's when and how to do it.",
    date:    "2025-03-15",
    readMin: 4,
    tag:     "Formats",
  },
];
