// lib/content/blogPosts.ts

export const BLOG_POSTS = [
  // ── Existing posts ────────────────────────────────────────────────────────
  {
    slug: "how-to-compress-images-for-web",
    title: "How to Compress Images for Web (JPG, PNG, WebP)",
    excerpt: "Images are the single biggest contributor to slow page load times. Learn the right compression settings for every format.",
    tag: "Images",
    date: "2025-01-15",
    readMin: 6,
  },
  {
    slug: "reduce-pdf-file-size",
    title: "5 Ways to Reduce PDF File Size",
    excerpt: "A PDF too large to email? Here are five methods to reduce PDF file size, starting with the fastest free options.",
    tag: "PDF",
    date: "2025-01-22",
    readMin: 5,
  },
  {
    slug: "jpg-vs-png-vs-webp",
    title: "JPG vs PNG vs WebP: Which Format Should You Use?",
    excerpt: "Choosing the wrong image format is one of the most common reasons websites are slower than they should be.",
    tag: "Images",
    date: "2025-02-01",
    readMin: 5,
  },
  {
    slug: "compress-images-for-email",
    title: "How to Compress Images for Email Attachments",
    excerpt: "Most email providers limit attachments to 10–25 MB. Here's how to compress images so they always go through.",
    tag: "Images",
    date: "2025-02-10",
    readMin: 4,
  },
  {
    slug: "what-is-webp",
    title: "What Is WebP? The Web Image Format Explained",
    excerpt: "In 2010, Google released WebP to make images smaller without looking worse. Here's everything you need to know.",
    tag: "Images",
    date: "2025-02-20",
    readMin: 6,
  },
  {
    slug: "merge-pdf-guide",
    title: "How to Merge PDFs for Free (No Software Needed)",
    excerpt: "Whether you're combining a contract with its exhibits or assembling a portfolio — here's how to merge PDFs in under a minute.",
    tag: "PDF",
    date: "2025-03-01",
    readMin: 4,
  },

  // ── New posts ─────────────────────────────────────────────────────────────
  {
    slug: "split-pdf-guide",
    title: "How to Split a PDF Into Separate Pages or Sections",
    excerpt: "Need just a few pages from a 100-page report? Learn how to split any PDF in seconds — no software required.",
    tag: "PDF",
    date: "2025-03-10",
    readMin: 4,
  },
  {
    slug: "image-compression-quality-vs-size",
    title: "Image Compression: Finding the Perfect Quality vs. Size Balance",
    excerpt: "Compress too much and images look bad. Compress too little and your site stays slow. Here's how to find the sweet spot.",
    tag: "Images",
    date: "2025-03-18",
    readMin: 5,
  },
  {
    slug: "convert-png-to-jpg",
    title: "How to Convert PNG to JPG (and When You Should)",
    excerpt: "Converting PNG to JPG can cut file sizes by 60–80%. Here's when it makes sense — and when it doesn't.",
    tag: "Images",
    date: "2025-03-25",
    readMin: 4,
  },
  {
    slug: "pdf-vs-word-which-to-send",
    title: "PDF vs Word Document: Which Should You Send?",
    excerpt: "Sending the wrong format can cause formatting chaos for the recipient. Here's a clear guide on when to use PDF vs DOCX.",
    tag: "PDF",
    date: "2025-04-02",
    readMin: 4,
  },
  {
    slug: "compress-images-for-social-media",
    title: "How to Compress Images for Social Media Without Losing Quality",
    excerpt: "Every social platform re-compresses your images on upload. Here's how to pre-optimize them so they still look great.",
    tag: "Images",
    date: "2025-04-10",
    readMin: 5,
  },
  {
    slug: "reduce-image-size-without-losing-quality",
    title: "How to Reduce Image Size Without Losing Quality",
    excerpt: "There are several techniques to shrink image files while keeping them sharp. This guide covers all of them.",
    tag: "Images",
    date: "2025-04-18",
    readMin: 6,
  },
  {
    slug: "core-web-vitals-images",
    title: "How Images Affect Your Core Web Vitals Score",
    excerpt: "LCP, CLS, and FID are all affected by how you handle images. Here's what to fix first for a faster score.",
    tag: "Performance",
    date: "2025-04-28",
    readMin: 6,
  },
  {
    slug: "batch-compress-images",
    title: "How to Batch Compress Multiple Images at Once",
    excerpt: "Compressing images one by one is tedious. Learn how to process dozens of images in a single step.",
    tag: "Images",
    date: "2025-05-06",
    readMin: 3,
  },
  {
    slug: "pdf-compression-explained",
    title: "How PDF Compression Actually Works (And What It Can't Fix)",
    excerpt: "Not all PDFs compress the same way. Understanding what's inside your PDF helps you pick the right approach.",
    tag: "PDF",
    date: "2025-05-14",
    readMin: 5,
  },
  {
    slug: "avif-vs-webp",
    title: "AVIF vs WebP: Which Next-Gen Image Format Wins in 2025?",
    excerpt: "AVIF is newer and even smaller than WebP. But should you switch? Here's an honest comparison.",
    tag: "Images",
    date: "2025-05-22",
    readMin: 6,
  },
];